# Site settings
title: Unknown
email: adamcurtisvt@gmail.com
description: > #
url: "https://adamcurtis.io"
twitter_username: AdamCurtisVT
github_username:  AdamCurtisVT

permalink: /:categories/:year/:month/:day/:title/
contenturl: "/blog/content/"
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
excerpt_separator: <!--more-->

plugins:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
